# The maximum amount of homes a player can have
maxHomes: 3

# The language to use. All language files must be in format language.lang.yml e.g. en.lang.yml
language: en

# The configuration type to use. Supported providers: (yml)
storage: yml